### ISSUE TITLE
On-screen artifact on some maps

### ISSUE THREAD

**Issue by Annihilator** [ravimohan1991/SmartCTF#4]
A player has noticed that this artifact appears on the top right of the screen, but only on certain maps:
![image](https://user-images.githubusercontent.com/760349/86510096-24c4d680-bded-11ea-929e-003b0073b7a4.png)
Example maps where it occurs:
* VCTF-OL-Dawn
* VCTF-Urban-LE

The issue is consistent when the SmartCTF is running, and disappears when it's removed.
Looks like the map thumbnail and appears on the HUD after spawning.

**Comment by ravimohan1991** [comment]
Good catch! I actually wanted to add a feature which shows the location of friend flag carrier within the map on team players' HUD.  Just like it is shown in ONS. But it turns out that the map is drawn only if `Level.RadarMapImage` is set by the map author. 

Since is it not set for most of the CTF/VCFT maps, it is never drawn on the HUD and, thus, I couldn't complete the feature. With time, I forgot about it. 

I have commented out the code which draws the map thumbnail. It should work fine now. 
[System.zip](https://github.com/ravimohan1991/SmartCTF/files/4874414/System.zip)

**Comment by Annihilator** [comment]
Issue fixed, thank you!
